"""
Django settings for bible_research project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys
from pathlib import Path
import textwrap

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ALLOWED_HOSTS = ["*"]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'drf_spectacular',

    # My apps
    'bible.apps.BibleConfig',
    'annotations.apps.AnnotationsConfig',
    'users.apps.UsersConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'bible_research.middleware.DeviceAndCountryMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

# Allow all Vercel automatically deployed PR preview origins
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*-vincent-uches-projects\.vercel\.app$",
]

ROOT_URLCONF = 'bible_research.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bible_research.wsgi.application'


# --- Environment-Specific Configuration ---

IS_GCP_ENVIRONMENT = (
    os.environ.get('GAE_APPLICATION') is not None
    or os.environ.get('K_SERVICE') is not None
    or os.environ.get('CLOUD_RUN_JOB') is not None
)
IS_VERCEL = os.environ.get('VERCEL') == '1'

if IS_GCP_ENVIRONMENT:
    # --- Production on Google Cloud ---
    from .gcp import get_secret

    SECRET_KEY = get_secret('DJANGO_SECRET_KEY')
    DBT_KEY = get_secret('DBT_KEY')
    ESV_KEY = get_secret('ESV_KEY')
    # Optional until an API.Bible key is provisioned — fall back
    # to a plain env var so the missing Secret Manager entry can
    # never break startup.
    API_BIBLE_KEY = os.environ.get('API_BIBLE_KEY')
    if not API_BIBLE_KEY:
        try:
            API_BIBLE_KEY = get_secret('API_BIBLE_KEY')
        except Exception:
            API_BIBLE_KEY = None
    DEBUG = False

    # Assumes DATABASE_URL is stored in Secret Manager
    database_url = get_secret('DATABASE_URL')
    db_config = dj_database_url.parse(database_url)

    # Handle SSL certificate from Secret Manager
    db_ssl_cert_content = get_secret('DB_SSL_CERT')
    if db_ssl_cert_content:
        CA_PEM_PATH = '/tmp/ca.pem'
        if not os.path.exists(CA_PEM_PATH):
            # The content from Secret Manager should already be formatted
            with open(CA_PEM_PATH, 'w') as f:
                f.write(db_ssl_cert_content)

        db_config.setdefault('OPTIONS', {})
        db_config['OPTIONS']['sslmode'] = 'require'
        db_config['OPTIONS']['sslrootcert'] = CA_PEM_PATH
    DATABASES = {'default': db_config}

    _audio_settings_source = os.environ

elif IS_VERCEL:
    # --- Production on Vercel ---
    SECRET_KEY = os.environ.get('SECRET_KEY')
    DBT_KEY = os.environ.get('DBT_KEY')
    ESV_KEY = os.environ.get('ESV_KEY')
    API_BIBLE_KEY = os.environ.get('API_BIBLE_KEY')
    DEBUG = os.environ.get('DEBUG', 'False') == 'True'

    # Build database config from individual env vars
    db_config = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }

    # Create ca.pem at runtime if database cert is provided
    CA_PEM_PATH = None
    capem_content = os.environ.get('DB_SSL_CERT')
    if capem_content:
        CA_PEM_PATH = '/tmp/ca.pem'
        if not os.path.exists(CA_PEM_PATH):
            if '\n' not in capem_content:
                lines = capem_content.replace(
                    "-----BEGIN CERTIFICATE----- ",
                    "-----BEGIN CERTIFICATE-----\n"
                )
                lines = lines.replace(
                    " -----END CERTIFICATE-----",
                    "\n-----END CERTIFICATE-----"
                )
                parts = lines.split("\n")
                if len(parts) >= 3:
                    base64_content = ''.join(parts[1:-1]).replace(' ', '')
                    formatted_content = textwrap.fill(base64_content, 64)
                    pem_content = (
                        f"-----BEGIN CERTIFICATE-----\n"
                        f"{formatted_content}\n"
                        f"-----END CERTIFICATE-----"
                    )
                else:
                    pem_content = capem_content
            else:
                pem_content = capem_content

            with open(CA_PEM_PATH, 'w') as f:
                f.write(pem_content)

        db_config['OPTIONS'] = {
            'sslmode': 'require',
            'sslrootcert': CA_PEM_PATH
        }

    DATABASES = {'default': db_config}

    _audio_settings_source = os.environ

else:
    # --- Local Development ---
    import yaml
    CONFIG_FILE = BASE_DIR / 'config.yaml'
    if not CONFIG_FILE.exists():
        raise FileNotFoundError(
            'config.yaml not found. Please create it from config_template.yaml'
        )

    with open(CONFIG_FILE, 'r') as f:
        config = yaml.safe_load(f)

    SECRET_KEY = config.get('SECRET_KEY')
    DBT_KEY = config.get('DBT_KEY')
    ESV_KEY = config.get('ESV_KEY')
    API_BIBLE_KEY = config.get('API_BIBLE_KEY')
    DEBUG = config.get('DEBUG', True)
    DATABASES = config.get('DATABASES')

    if DATABASES and 'default' in DATABASES:
        opts = DATABASES['default'].get('OPTIONS', {})
        if 'sslrootcert' in opts:
            cert_path = opts['sslrootcert']
            opts['sslrootcert'] = str(BASE_DIR / cert_path)

    _audio_settings_source = config

# Tests always run on a local throwaway sqlite DB: the configured
# connection is a read-only user against production that cannot
# create the test database.
if 'test' in sys.argv:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Audio / Cloud TTS settings are resolved from a single source per
# environment (os.environ in cloud branches, the parsed config.yaml
# dict locally). Both support .get(key, default), so one block covers
# all three environments without duplication.
_default_bucket = (
    f"{os.environ.get('GOOGLE_CLOUD_PROJECT', 'bible-research-489314')}"
    "-bible-audio"
)
GOOGLE_TTS_LANGUAGE_CODE = _audio_settings_source.get(
    "GOOGLE_TTS_LANGUAGE_CODE", "lv-LV"
)
GOOGLE_TTS_VOICE_NAME = _audio_settings_source.get(
    "GOOGLE_TTS_VOICE_NAME", "lv-LV-Chirp3-HD-Sadachbia"
)
GOOGLE_TTS_SAMPLE_RATE_HERTZ = int(
    _audio_settings_source.get("GOOGLE_TTS_SAMPLE_RATE_HERTZ", 24000)
)
AUDIO_BUCKET_NAME = _audio_settings_source.get(
    "AUDIO_BUCKET_NAME", _default_bucket
)
AUDIO_SIGNED_URL_TTL_SECONDS = int(
    _audio_settings_source.get("AUDIO_SIGNED_URL_TTL_SECONDS", 3600)
)
MONTHLY_TTS_CHAR_LIMIT = int(
    _audio_settings_source.get("MONTHLY_TTS_CHAR_LIMIT", 100000)
)
LOCK_STALE_HOURS = int(
    _audio_settings_source.get("LOCK_STALE_HOURS", 24)
)

_gcp_project = os.environ.get(
    "GOOGLE_CLOUD_PROJECT", "bible-research-489314"
)
IMAGE_BUCKET_ORIGINALS = os.environ.get(
    "IMAGE_BUCKET_ORIGINALS",
    f"{_gcp_project}-images-originals",
)
IMAGE_BUCKET_THUMBNAILS = os.environ.get(
    "IMAGE_BUCKET_THUMBNAILS",
    f"{_gcp_project}-images-thumbnails",
)
IMAGE_MAX_BYTES = int(
    os.environ.get("IMAGE_MAX_BYTES", 10 * 1024 * 1024)
)
IMAGE_SIGNED_URL_TTL_SECONDS = int(
    os.environ.get("IMAGE_SIGNED_URL_TTL_SECONDS", 600)
)
IMAGE_ALLOWED_CONTENT_TYPES = (
    "image/jpeg",
    "image/png",
    "image/webp",
    "image/gif",
)
IMAGE_MAX_PER_NOTE = int(
    os.environ.get("IMAGE_MAX_PER_NOTE", 10)
)
IMAGE_MAX_PER_COMMENT = int(
    os.environ.get("IMAGE_MAX_PER_COMMENT", 5)
)

# Ensure DBT_KEY is available as an environment variable if it exists
if DBT_KEY:
    os.environ['DBT_KEY'] = DBT_KEY


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'users.backends.CaseInsensitiveAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'MinimumLengthValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'CommonPasswordValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'NumericPasswordValidator'
        ),
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles', 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'bible_research.authentication.BearerTokenAuthentication',
        (
            'bible_research.authentication.'
            'CSRFExemptSessionAuthentication'
        ),
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Bible Research API',
    'DESCRIPTION': 'API for the Bible Research project',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
    },
}

# Logging configuration for production and development.
# This sends logs to the console, where platforms like GCP/Vercel can
# capture them. File logging is removed as it's not suitable for
# read-only filesystems.

def create_log_handler(
    handler_name, level, filename=None, max_bytes=10485760,
    backup_count=10
):
    # Only configure file logging for local development.
    # GAE and Vercel have read-only filesystems.
    is_local_dev = not IS_GCP_ENVIRONMENT and not IS_VERCEL
    if DEBUG and filename and is_local_dev:
        logs_dir = os.path.join(BASE_DIR, 'logs')
        if not os.path.exists(logs_dir):
            os.makedirs(logs_dir)

        return {
            'level': level,
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', filename),
            'maxBytes': max_bytes,  # 10MB
            'backupCount': backup_count,
            'formatter': 'verbose',
        }
    else:
        return {
            'level': level,
            'class': 'logging.NullHandler',
        }


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': (
                '{levelname} {asctime} {module} {process:d} '
                '{thread:d} {message}'
            ),
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file_debug': create_log_handler('file_debug', 'DEBUG', 'debug.log'),
        'file_error': create_log_handler('file_error', 'ERROR', 'error.log'),
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file_debug'],
            'level': 'INFO',
            'propagate': True,
        },
        'bible': {
            'handlers': ['console', 'file_debug'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'annotations': {
            'handlers': ['console', 'file_debug'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': True,
        }
    },
}
